### ISSUE TITLE
Update check stopped working

### ISSUE THREAD

**Issue by hemlok89** [lolamtisch/MALSync#239]
Suddenly the extension stopped checking for updates. I opened the debugging section & all were red. I reinstalled. Tried setting the check interval to off & on. Finally I cleared all the tags from MAL. Then I read one chapter from a manga to register it in MalSync. Then tried checking but same red error.

I tried setting the website for kissmanga, manganelo & mangadex. Also animes are having same problem.

**Additional information:**
 - Browser: Chrome
 - Type: Extension
 - Url:

**Comment by henrik9999** [comment]
#216

**Comment by henrik9999** [comment]
fixed next release

**Comment by lolamtisch** [comment]
Should be fixed in version 0.6.8

**Comment by hemlok89** [comment]
The update is not available on Chrome store yet.

**Comment by henrik9999** [comment]
seems like chrome is taking their time again with approving

**Comment by lolamtisch** [comment]
The update just got approved

**Comment by hemlok89** [comment]
The problem is still happening.

[Screen 1](https://i.imgur.com/IeSoxIp.png)
[Screen 2](https://i.imgur.com/Lw8lFto.png)

**Comment by hemlok89** [comment]
Tried the extension on a fresh profile on Edge beta. Working fine. Thank you!
